import 'package:get_storage/get_storage.dart';
import 'api_client.dart';

class AuthService {
  final ApiClient _api = ApiClient();
  final GetStorage _storage = GetStorage();

  // In a real implementation OTP is generated by the backend and sent to the
  // user's phone. Here we simply cache the last code for demo purposes.
  String? _cachedOtp;
  String? _cachedPhone;

  Future<void> sendOtp(String phone) async {
    // call backend endpoint or simulate
    try {
      final response = await _api.post("/send-otp", {"phone": phone});
      // backend may return the OTP for testing
      if (response is Map && response.containsKey('otp')) {
        _cachedOtp = response['otp'].toString();
      }
    } catch (_) {
      // fallback simulation
      _cachedOtp = (100000 + (DateTime.now().millisecondsSinceEpoch % 899999)).toString();
    }
    _cachedPhone = phone;
    // not storing OTP persistently
  }

  Future<void> verifyOtp(String phone, String otp) async {
    if (_cachedPhone == phone && _cachedOtp == otp) {
      // simulate successful verification and issue token
      _storage.write('token', 'demo-token');
    } else {
      // try calling backend verification if available
      final response = await _api.post("/verify-otp", {"phone": phone, "otp": otp});
      if (response is Map && response.containsKey('access_token')) {
        _storage.write('token', response['access_token']);
      } else {
        throw Exception('Invalid OTP');
      }
    }
  }

  Future<void> registerUser(String name, String email, String phone) async {
    // send registration to backend, assume it sends OTP
    await _api.post("/register", {
      "name": name,
      "email": email,
      "phone": phone,
    });
    // We'll ask caller to send/verify OTP afterwards
  }

  void logout() {
    _storage.remove("token");
  }

  bool get isLoggedIn => _storage.read("token") != null;
}
