name: user_a
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1


  # 🔥 REQUIRED FOR DATE PICKER + RTL + MATERIAL LOCALIZATION
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

http: ^1.2.2

